# site properties and page defaults
title: “The Sub-3Sec Problem: From Text-Independent to Text-Dependent Corpus”
subtitle:  The Sub3Vox Dataset
description: A website for displaying tdsv datasets
header: images/EEE background.jpg
footer: images/EEE background.jpg
proofer: false

# site social media and other links
links:
  email: 23131557r@connect.polyu.hk
  orcid: 0000-0001-8713-9213
  google-scholar: https://scholar.google.com/citations?user=SZegiA4AAAAJ&hl=en
  github: https://sites.google.com/view/kongaiklee
  twitter: slash1028DESCRIPTION=An engaging 1-3 sentence description of your lab.
  youtube: slash1028DESCRIPTION=An engaging 1-3 sentence description of your lab.

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
